source 'https://github.com/noughts/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'NNAlertView', :exclusive => true do
  pod "NNAlertView", :path => "../"
  pod "NBULog"
end

target 'Tests', :exclusive => true do
  pod "NNAlertView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
